# Generated by Django 3.0.4 on 2020-12-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0011_auto_20201207_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_of_user_note',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
