# Generated by Django 3.0.4 on 2020-12-11 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0012_profile_num_of_user_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='num_of_user_note',
            new_name='updatednum_of_user_note',
        ),
    ]
